csrs1:
  image: mongo:3.2
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/mongodb/cs/rs1:/data/db
  privileged: true
  ports:
    - '828:27017'
  mem_limit: 100000000
  cpu_shares: 7

csrs2:
  image: mongo:3.2
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/mongodb/cs/rs2:/data/db
  privileged: true
  ports:
    - '827:27017'
  # mem_limit: 100000000
  # cpu_shares: 7

csrs3:
  image: mongo:3.2
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/mongodb/cs/rs3:/data/db
  privileged: true
  ports:
    - '826:27017'
  # mem_limit: 100000000
  # cpu_shares: 7
