master:
  image: mongo:3.2
  volumes:
    - /etc/localtime:/etc/localtime
    - ~/data/mongodb/master:/data/db
  privileged: true
  ports:
    - '828:27017'
  command: mongod --dbpath /data/db  --replSet pictureAir
  mem_limit: 100000000
  cpu_shares: 7

rs2:
  image: mongo:3.2
  volumes:
    - /etc/localtime:/etc/localtime
    - ~/data/mongodb/rs2:/data/db
  privileged: true
  ports:
    - '827:27017'
  command: mongod --dbpath /data/db  --replSet pictureAir
  # mem_limit: 100000000
  # cpu_shares: 7

rs3:
  image: mongo:3.2
  volumes:
    - /etc/localtime:/etc/localtime
    - ~/data/mongodb/rs3:/data/db
  privileged: true
  ports:
    - '826:27017'
  command: mongod --dbpath /data/db  --replSet pictureAir
  # mem_limit: 100000000
  # cpu_shares: 7
